/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSurveysIndexRouteImport } from './routes/_authenticated/surveys.index'
import { Route as AuthenticatedSurveysIdRouteImport } from './routes/_authenticated/surveys.$id'
import { Route as ApiChatSurveysIdRouteImport } from './routes/api/chat.surveys.$id'
import { Route as AuthenticatedSurveysIdEditRouteImport } from './routes/_authenticated/surveys.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSurveysIndexRoute =
  AuthenticatedSurveysIndexRouteImport.update({
    id: '/surveys/',
    path: '/surveys/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSurveysIdRoute = AuthenticatedSurveysIdRouteImport.update({
  id: '/surveys/$id',
  path: '/surveys/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatSurveysIdRoute = ApiChatSurveysIdRouteImport.update({
  id: '/api/chat/surveys/$id',
  path: '/api/chat/surveys/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSurveysIdEditRoute =
  AuthenticatedSurveysIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSurveysIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/s/$slug': typeof SSlugRoute
  '/surveys/$id': typeof AuthenticatedSurveysIdRouteWithChildren
  '/surveys/': typeof AuthenticatedSurveysIndexRoute
  '/surveys/$id/edit': typeof AuthenticatedSurveysIdEditRoute
  '/api/chat/surveys/$id': typeof ApiChatSurveysIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/s/$slug': typeof SSlugRoute
  '/surveys/$id': typeof AuthenticatedSurveysIdRouteWithChildren
  '/surveys': typeof AuthenticatedSurveysIndexRoute
  '/surveys/$id/edit': typeof AuthenticatedSurveysIdEditRoute
  '/api/chat/surveys/$id': typeof ApiChatSurveysIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/s/$slug': typeof SSlugRoute
  '/_authenticated/surveys/$id': typeof AuthenticatedSurveysIdRouteWithChildren
  '/_authenticated/surveys/': typeof AuthenticatedSurveysIndexRoute
  '/_authenticated/surveys/$id/edit': typeof AuthenticatedSurveysIdEditRoute
  '/api/chat/surveys/$id': typeof ApiChatSurveysIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/s/$slug'
    | '/surveys/$id'
    | '/surveys/'
    | '/surveys/$id/edit'
    | '/api/chat/surveys/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/s/$slug'
    | '/surveys/$id'
    | '/surveys'
    | '/surveys/$id/edit'
    | '/api/chat/surveys/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/s/$slug'
    | '/_authenticated/surveys/$id'
    | '/_authenticated/surveys/'
    | '/_authenticated/surveys/$id/edit'
    | '/api/chat/surveys/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SSlugRoute: typeof SSlugRoute
  ApiChatSurveysIdRoute: typeof ApiChatSurveysIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/surveys/': {
      id: '/_authenticated/surveys/'
      path: '/surveys'
      fullPath: '/surveys/'
      preLoaderRoute: typeof AuthenticatedSurveysIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/surveys/$id': {
      id: '/_authenticated/surveys/$id'
      path: '/surveys/$id'
      fullPath: '/surveys/$id'
      preLoaderRoute: typeof AuthenticatedSurveysIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat/surveys/$id': {
      id: '/api/chat/surveys/$id'
      path: '/api/chat/surveys/$id'
      fullPath: '/api/chat/surveys/$id'
      preLoaderRoute: typeof ApiChatSurveysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/surveys/$id/edit': {
      id: '/_authenticated/surveys/$id/edit'
      path: '/edit'
      fullPath: '/surveys/$id/edit'
      preLoaderRoute: typeof AuthenticatedSurveysIdEditRouteImport
      parentRoute: typeof AuthenticatedSurveysIdRoute
    }
  }
}

interface AuthenticatedSurveysIdRouteChildren {
  AuthenticatedSurveysIdEditRoute: typeof AuthenticatedSurveysIdEditRoute
}

const AuthenticatedSurveysIdRouteChildren: AuthenticatedSurveysIdRouteChildren =
  {
    AuthenticatedSurveysIdEditRoute: AuthenticatedSurveysIdEditRoute,
  }

const AuthenticatedSurveysIdRouteWithChildren =
  AuthenticatedSurveysIdRoute._addFileChildren(
    AuthenticatedSurveysIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSurveysIdRoute: typeof AuthenticatedSurveysIdRouteWithChildren
  AuthenticatedSurveysIndexRoute: typeof AuthenticatedSurveysIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSurveysIdRoute: AuthenticatedSurveysIdRouteWithChildren,
  AuthenticatedSurveysIndexRoute: AuthenticatedSurveysIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SSlugRoute: SSlugRoute,
  ApiChatSurveysIdRoute: ApiChatSurveysIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
